In [4]:
import numpy as np

# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)

15
[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]
 [0.53490572 0.39850092 0.17338873]
 [0.49258141 0.61159319 0.34017639]
 [0.13462167 0.21991724 0.45820622]
 [0.34552327 0.94135983 0.26936348]
 [0.15183663 0.43999062 0.99088187]
 [0.64550284 0.39714294 0.91977134]
 [0.74691195 0.28419631 0.22629985]
 [0.17047699 0.6970324  0.14916943]
 [0.22054934 0.29782524 0.34355534]
 [0.66601366 0.67198515 0.2462953 ]
 [0.04680895 0.23136024 0.77061759]
 [0.60009728 0.72513573 0.06608864]
 [0.96599485 0.86111969 0.56682913]]
15
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837]


In [3]:
def print_csv(arr):
    """
    Print a NumPy array as CSV:
    - One row per line
    - Comma-separated columns
    - If there's only one row, print each value on a new line
    """
    arr = np.asarray(arr)

    if arr.ndim == 0:
        # Scalar
        print(str(arr.item()))

    elif arr.ndim == 1:
        # 1D: treat as single row → print each value on its own line
        for val in arr:
            print(str(val))

    elif arr.ndim == 2:
        if arr.shape[0] == 1:
            # Single row → print each column value on its own line
            for val in arr[0]:
                print(str(val))
        else:
            # Multiple rows → print comma-separated
            for row in arr:
                print(','.join(map(str, row)))

    else:
        # 3D+ → flatten each leading slice to a row
        reshaped = arr.reshape(arr.shape[0], -1)
        for row in reshaped:
            print(','.join(map(str, row)))
print_csv(inputs)
print_csv(outputs)

0.1715252068810621,0.3439168702758373,0.2487372010692387
0.2421144606124933,0.6440742697791076,0.27243280919945523
0.5349057202251034,0.39850091536763166,0.17338872894567725
0.49258141463713434,0.6115931882759961,0.3401763860035727
0.13462166632061112,0.2199172404897456,0.45820621964922703
0.3455232705197697,0.9413598305723256,0.2693634790694064
0.151836632374168,0.43999061896644376,0.990881866558951
0.6455028351793182,0.3971429395797703,0.9197713377032198
0.7469119451655177,0.28419630922573424,0.22629985488752546
0.17047699396968063,0.697032400686134,0.14916943370830027
0.2205493370831766,0.2978252442230862,0.34355534441672586
0.6660136587669346,0.6719851513369297,0.2462952966705313
0.046808949722497384,0.2313602407834674,0.7706175921643
0.6000972824185008,0.7251357252228826,0.06608864149534865
0.9659948489488087,0.8611196897300882,0.5668291312870885
-0.11212220046256897
-0.08796286022736445
-0.111414654295324
-0.034835313350078584
-0.04800758439218157
-0.11062091307282658
-0.39892551