In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import clear_output
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler


In [2]:
# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)


30
[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880

In [ ]:
#Append week-1 data.
#Function 7:	[0.000000, 0.500000, 0.214286, 0.214286, 0.428572, 0.714286]
inputs = np.append(inputs, [[0.000000, 0.500000, 0.214286, 0.214286, 0.428572, 0.714286]], axis=0)
#Function 7:	1.181422704250112
outputs = np.append(outputs, [1.181422704250112], axis=0)

31
[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880

In [ ]:
#Append week-2 data.
#Function 7:	[0.060606, 0.484848, 0.242424, 0.181818, 0.484848, 0.727273]
inputs = np.append(inputs, [[0.060606, 0.484848, 0.242424, 0.181818, 0.484848, 0.727273]], axis=0)
#Function 7:	0.9769171261966855
outputs = np.append(outputs, [0.9769171261966855], axis=0)

In [ ]:
print(len(inputs))
print(inputs)
print(len(outputs))
print(outputs)

In [4]:
X = inputs
y = outputs

In [5]:
%run ../common_functions.ipynb
# Initialize result collection
query_results = []

In [6]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.01, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.24242424 0.42424242 0.72727273]


In [7]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.05, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.05, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.24242424 0.42424242 0.72727273]


In [8]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.1, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.24242424 0.42424242 0.72727273]


In [9]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=1.0, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 1.0, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.24242424 0.42424242 0.72727273]


In [10]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=2.0, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 2.0, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.54545455 0.24242424 0.24242424 0.42424242 0.72727273]


In [11]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=3.0, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 3.0, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.18181818 0.48484848 0.72727273]


In [12]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.18181818 0.42424242 0.72727273]


In [13]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.05, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.05, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.18181818 0.42424242 0.72727273]


In [14]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  6
Dimension of input space: 6
Each axis has 100 points before downsampling
Each axis has 17 points after downsampling
Function will evaluate across: 24137569 points
Mean  24137569
Std   24137569
Next query point: [0.06060606 0.48484848 0.24242424 0.18181818 0.42424242 0.72727273]


In [15]:
find_best_candidate(query_results)

Total number of points to evaluate: 9
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.06060606, 0.48484848, 0.24242424, 0.24242424, 0.42424242,
       0.72727273]), 'score': np.float64(0.3175232041320627), 'dim': 6}
{'method': 'PI', 'xi': 0.05, 'kappa': None, 'x': array([0.06060606, 0.48484848, 0.24242424, 0.24242424, 0.42424242,
       0.72727273]), 'score': np.float64(0.2647594675119357), 'dim': 6}
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.06060606, 0.48484848, 0.24242424, 0.24242424, 0.42424242,
       0.72727273]), 'score': np.float64(0.20571744627266192), 'dim': 6}
{'method': 'UCB', 'xi': None, 'kappa': 1.0, 'x': array([0.06060606, 0.48484848, 0.24242424, 0.24242424, 0.42424242,
       0.72727273]), 'score': np.float64(3.4011437953553036), 'dim': 6}
{'method': 'UCB', 'xi': None, 'kappa': 2.0, 'x': array([0.06060606, 0.54545455, 0.24242424, 0.24242424, 0.42424242,
       0.72727273]), 'score': np.float64(3.8277348347644695), 'dim': 6}
{'method': 'UCB', 'xi':

{'method': 'UCB',
 'xi': None,
 'kappa': 3.0,
 'x': array([0.06060606, 0.48484848, 0.24242424, 0.18181818, 0.48484848,
        0.72727273]),
 'score': np.float64(4.431854992100594),
 'dim': 6}