In [3]:
import numpy as np

# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)

30
[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880

In [4]:
def print_csv(arr):
    """
    Print a NumPy array as CSV:
    - One row per line
    - Comma-separated columns
    - If there's only one row, print each value on a new line
    """
    arr = np.asarray(arr)

    if arr.ndim == 0:
        # Scalar
        print(str(arr.item()))

    elif arr.ndim == 1:
        # 1D: treat as single row → print each value on its own line
        for val in arr:
            print(str(val))

    elif arr.ndim == 2:
        if arr.shape[0] == 1:
            # Single row → print each column value on its own line
            for val in arr[0]:
                print(str(val))
        else:
            # Multiple rows → print comma-separated
            for row in arr:
                print(','.join(map(str, row)))

    else:
        # 3D+ → flatten each leading slice to a row
        reshaped = arr.reshape(arr.shape[0], -1)
        for row in reshaped:
            print(','.join(map(str, row)))
print_csv(inputs)
print_csv(outputs)

0.2726238220336933,0.3244953623087271,0.8971088103082926,0.8329511521103058,0.1540626853924547,0.7958636234722036
0.5430025769847714,0.9246939036961066,0.3415674591580987,0.6464858491139559,0.7184403268342174,0.343132663729359
0.09083224802375334,0.661529381768249,0.0659309106387106,0.2585770079605848,0.9634528513541345,0.6402653979255966
0.11886697487294917,0.6150549401610158,0.905816385208328,0.8553003035780179,0.41363142879453507,0.5852356278450974
0.6302176411815951,0.8380968963061266,0.6800130516496496,0.7318950900926644,0.5267367145175407,0.3484292133580069
0.7649191728046694,0.25588291701198074,0.6090842238764527,0.21807904189508076,0.3229427691734139,0.09579365511638072
0.057895541971385245,0.49167221863901367,0.24742222374867484,0.21811843639837636,0.42042832954601583,0.7309698428701273
0.19525188113467162,0.07922665059137424,0.5545804616685562,0.17056681968240583,0.014944176429292355,0.10703171010323376
0.6423029815827472,0.8368745468225558,0.021792691485860827,0.101488009538