In [9]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import clear_output
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler


In [10]:
# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)


20
[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.7828798

In [ ]:
#Append week-1 data.
#Function 6:	[0.733334, 0.200000, 0.666667, 0.733334, 0.133334]
inputs = np.append(inputs, [[0.733334, 0.200000, 0.666667, 0.733334, 0.133334]], axis=0)
#Function 6:	-0.5377942602933444
outputs = np.append(outputs, [-0.5377942602933444], axis=0)

21
[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.7828798

In [ ]:
#Append week-2 data.
#Function 6:	[0.757576, 0.101010, 0.707071, 0.757576, 0.151515]
inputs = np.append(inputs, [[0.757576, 0.101010, 0.707071, 0.757576, 0.151515]], axis=0)
#Function 6:	-0.7102415173770004
outputs = np.append(outputs, [-0.7102415173770004], axis=0)

In [ ]:
print(len(inputs))
print(inputs)
print(len(outputs))
print(outputs)

In [12]:
X = inputs
y = outputs

In [13]:
%run ../common_functions.ipynb
# Initialize result collection
query_results = []

In [14]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.01, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.70707071 0.1010101 ]


In [15]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.05, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.05, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.70707071 0.1010101 ]


In [16]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.1, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.70707071 0.1010101 ]


In [17]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=1.0, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 1.0, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.75757576 0.1010101 ]


In [18]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=2.0, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 2.0, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.65656566 0.75757576 0.05050505]


In [19]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=3.0, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 3.0, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.75757576 0.1010101  0.70707071 0.75757576 0.15151515]


In [20]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.75757576 0.1010101 ]


In [21]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.05, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.05, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.75757576 0.1010101 ]


In [22]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1], apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  5
Dimension of input space: 5
Each axis has 100 points before downsampling
Each axis has 20 points after downsampling
Function will evaluate across: 3200000 points
Mean  3200000
Std   3200000
Next query point: [0.70707071 0.2020202  0.70707071 0.75757576 0.1010101 ]


In [23]:
find_best_candidate(query_results)

Total number of points to evaluate: 9
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.70707071, 0.2020202 , 0.70707071, 0.70707071, 0.1010101 ]), 'score': np.float64(0.41804261278582877), 'dim': 5}
{'method': 'PI', 'xi': 0.05, 'kappa': None, 'x': array([0.70707071, 0.2020202 , 0.70707071, 0.70707071, 0.1010101 ]), 'score': np.float64(0.38044189663121636), 'dim': 5}
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.70707071, 0.2020202 , 0.70707071, 0.70707071, 0.1010101 ]), 'score': np.float64(0.33502056386393864), 'dim': 5}
{'method': 'UCB', 'xi': None, 'kappa': 1.0, 'x': array([0.70707071, 0.2020202 , 0.70707071, 0.75757576, 0.1010101 ]), 'score': np.float64(2.2294709873828693), 'dim': 5}
{'method': 'UCB', 'xi': None, 'kappa': 2.0, 'x': array([0.70707071, 0.2020202 , 0.65656566, 0.75757576, 0.05050505]), 'score': np.float64(2.8299219795512416), 'dim': 5}
{'method': 'UCB', 'xi': None, 'kappa': 3.0, 'x': array([0.75757576, 0.1010101 , 0.70707071, 0.75757576, 0.15151515])

{'method': 'UCB',
 'xi': None,
 'kappa': 3.0,
 'x': array([0.75757576, 0.1010101 , 0.70707071, 0.75757576, 0.15151515]),
 'score': np.float64(3.6065814591350724),
 'dim': 5}