In [1]:
import numpy as np

# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)

20
[[0.7281861  0.15469257 0.73255167 0.69399651 0.05640131]
 [0.24238435 0.84409997 0.5778091  0.67902128 0.50195289]
 [0.72952261 0.7481062  0.67977464 0.35655228 0.67105368]
 [0.77062024 0.11440374 0.04677993 0.64832428 0.27354905]
 [0.6188123  0.33180214 0.18728787 0.75623847 0.3288348 ]
 [0.78495809 0.91068235 0.7081201  0.95922543 0.0049115 ]
 [0.14511079 0.8966846  0.89632223 0.72627154 0.23627199]
 [0.94506907 0.28845905 0.97880576 0.96165559 0.59801594]
 [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
 [0.75759436 0.35583141 0.0165229  0.4342072  0.11243304]
 [0.5367969  0.30878091 0.41187929 0.38822518 0.5225283 ]
 [0.95773967 0.23566857 0.09914585 0.15680593 0.07131737]
 [0.6293079  0.80348368 0.81140844 0.04561319 0.11062446]
 [0.02173531 0.42808424 0.83593944 0.48948866 0.51108173]
 [0.43934426 0.69892383 0.42682022 0.10947609 0.87788847]
 [0.25890557 0.79367771 0.6421139  0.19667346 0.59310318]
 [0.43216593 0.71561781 0.3418191  0.70499988 0.61496184]
 [0.7828798

In [2]:
def print_csv(arr):
    """
    Print a NumPy array as CSV:
    - One row per line
    - Comma-separated columns
    - If there's only one row, print each value on a new line
    """
    arr = np.asarray(arr)

    if arr.ndim == 0:
        # Scalar
        print(str(arr.item()))

    elif arr.ndim == 1:
        # 1D: treat as single row → print each value on its own line
        for val in arr:
            print(str(val))

    elif arr.ndim == 2:
        if arr.shape[0] == 1:
            # Single row → print each column value on its own line
            for val in arr[0]:
                print(str(val))
        else:
            # Multiple rows → print comma-separated
            for row in arr:
                print(','.join(map(str, row)))

    else:
        # 3D+ → flatten each leading slice to a row
        reshaped = arr.reshape(arr.shape[0], -1)
        for row in reshaped:
            print(','.join(map(str, row)))
print_csv(inputs)
print_csv(outputs)

0.7281861047460138,0.1546925696237983,0.7325516687239811,0.6939965090690888,0.056401310518258585
0.24238434723790758,0.8440999723462298,0.5778090988182423,0.6790212842838805,0.5019528879463457
0.7295226100931684,0.7481062003003915,0.6797746408949024,0.3565522793389573,0.6710536834597941
0.770620241725545,0.11440374416322774,0.0467799318531783,0.6483242845395736,0.2735490526883131
0.6188122987341569,0.33180213718420826,0.18728786777392725,0.756238474019041,0.3288347983365967
0.7849580941321159,0.9106823491056887,0.7081201035127033,0.9592254289504146,0.004911495864404647
0.14511078573766278,0.8966845977360148,0.8963222346125226,0.7262715366744776,0.23627199091209328
0.9450690681186655,0.28845905059517574,0.9788057635601997,0.9616555869902994,0.5980159363909763
0.12572015503019873,0.8627246921598651,0.028544332231059788,0.24660527193052817,0.7512062409044311
0.7575943553544202,0.35583141491553005,0.01652289968556364,0.43420720498662724,0.1124330443582503
0.5367969034860786,0.3087809072394