In [61]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import clear_output
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler


In [62]:
# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)


20
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]]
20
[6.44434399e+01 1.83013796e+01 1.12939795e-01 4.21089

In [ ]:
#Append week-1 data.
#Function 5:	[0.183674, 0.857143, 0.816327, 0.877551]
inputs = np.append(inputs, [[0.183674, 0.857143, 0.816327, 0.877551]], axis=0)
#Function 5:	872.3074873002278
outputs = np.append(outputs, [872.3074873002278], axis=0)

21
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.183674   0.857143   0.816327   0.877551  ]]
21
[6.444

In [ ]:
#Append week-2 data.
#Function 5:	[0.272727, 0.848484, 0.848485, 0.818182]
inputs = np.append(inputs, [[0.272727, 0.848484, 0.848485, 0.818182]], axis=0)
#Function 5:	743.1182481623213
outputs = np.append(outputs, [743.1182481623213], axis=0)

In [ ]:
print(len(inputs))
print(inputs)
print(len(outputs))
print(outputs)

In [64]:
X = inputs
y = outputs

In [65]:
%run ../common_functions.ipynb
# Initialize result collection
query_results = []

In [66]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.01, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.24242424 0.84848485 0.87878788 0.87878788]


In [67]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.05, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.05, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.24242424 0.84848485 0.87878788 0.87878788]


In [68]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.1, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.21212121 0.81818182 0.87878788 0.87878788]


In [69]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=1.0, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 1.0, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.21212121 0.81818182 0.87878788 0.87878788]


In [70]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=2.0, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 2.0, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.27272727 0.84848485 0.84848485 0.87878788]


In [71]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=3.0, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 3.0, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.27272727 0.84848485 0.84848485 0.81818182]


In [72]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.24242424 0.87878788 0.87878788 0.84848485]


In [73]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.05, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.05, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.21212121 0.81818182 0.87878788 0.84848485]


In [74]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
print("ACQ:", len(acq_vals))
print("Score:", score)
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.24242424 0.87878788 0.87878788 0.84848485]
ACQ: 1336336
Score: 0.039432778719641084


In [75]:
find_best_candidate(query_results)

Total number of points to evaluate: 9
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.24242424, 0.84848485, 0.87878788, 0.87878788]), 'score': np.float64(0.36465855316924745), 'dim': 4}
{'method': 'PI', 'xi': 0.05, 'kappa': None, 'x': array([0.24242424, 0.84848485, 0.87878788, 0.87878788]), 'score': np.float64(0.27885181355583927), 'dim': 4}
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.21212121, 0.81818182, 0.87878788, 0.87878788]), 'score': np.float64(0.20428909326128886), 'dim': 4}
{'method': 'UCB', 'xi': None, 'kappa': 1.0, 'x': array([0.21212121, 0.81818182, 0.87878788, 0.87878788]), 'score': np.float64(3.325435163071673), 'dim': 4}
{'method': 'UCB', 'xi': None, 'kappa': 2.0, 'x': array([0.27272727, 0.84848485, 0.84848485, 0.87878788]), 'score': np.float64(3.7566156240535795), 'dim': 4}
{'method': 'UCB', 'xi': None, 'kappa': 3.0, 'x': array([0.27272727, 0.84848485, 0.84848485, 0.81818182]), 'score': np.float64(4.373343625890351), 'dim': 4}
{'method': 'EI', 'xi'

{'method': 'UCB',
 'xi': None,
 'kappa': 3.0,
 'x': array([0.27272727, 0.84848485, 0.84848485, 0.81818182]),
 'score': np.float64(4.373343625890351),
 'dim': 4}