In [3]:
import numpy as np

# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
#print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
#print(len(outputs))
print(outputs)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]]
[6.44434399e+01 1.83013796e+01 1.12939795e-01 4.21089813e+0

In [4]:
def print_csv(arr):
    """
    Print a NumPy array as CSV:
    - One row per line
    - Comma-separated columns
    - If there's only one row, print each value on a new line
    """
    arr = np.asarray(arr)

    if arr.ndim == 0:
        # Scalar
        print(str(arr.item()))

    elif arr.ndim == 1:
        # 1D: treat as single row → print each value on its own line
        for val in arr:
            print(str(val))

    elif arr.ndim == 2:
        if arr.shape[0] == 1:
            # Single row → print each column value on its own line
            for val in arr[0]:
                print(str(val))
        else:
            # Multiple rows → print comma-separated
            for row in arr:
                print(','.join(map(str, row)))

    else:
        # 3D+ → flatten each leading slice to a row
        reshaped = arr.reshape(arr.shape[0], -1)
        for row in reshaped:
            print(','.join(map(str, row)))
print_csv(inputs)
print_csv(outputs)

0.1914470844571281,0.03819337135150802,0.6074178108720669,0.4145841369758819
0.7586529492430261,0.5365177380716337,0.6560003817255494,0.36034155302921755
0.43834987265310876,0.8043397048222797,0.21024526639869967,0.15129481609432094
0.7060508340594309,0.5341919611519633,0.2642433451718953,0.48208754903709394
0.8364779930351233,0.19360964686178006,0.6638926969585176,0.7856488828898288
0.6834322498676915,0.11866264178849073,0.8290459096967396,0.5675766059352313
0.553621479516824,0.6673499787364745,0.3238058191550842,0.8148697537245304
0.35235626946595233,0.32224153197183136,0.11697936758857319,0.4731125215557709
0.15378570594381347,0.7293816904129607,0.4225984366784806,0.4430741656488165
0.46344226738528294,0.630024510146729,0.10790645581865044,0.957643898670113
0.6774911484129013,0.3585095065455117,0.47959222446529515,0.07288048110014078
0.5839734124984879,0.1472426461525712,0.34809746209352754,0.4286146510285499
0.3068887187315784,0.3168781265532129,0.6226344812966896,0.095399058106317