In [47]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import clear_output
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler


In [48]:
# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)


30
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.170347

In [ ]:
#Append week-1 data.
#Function 4:	[0.469388, 0.448980, 0.469388, 0.204082]
inputs = np.append(inputs, [[0.469388, 0.448980, 0.469388, 0.204082]], axis=0)
#Function 4:	-4.620232320523549
outputs = np.append(outputs, [-4.620232320523549], axis=0)

31
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.170347

In [ ]:
#Append week-2 data.
#Function 4:	[0.515152, 0.484848, 0.363636, 0.181819]
inputs = np.append(inputs, [[0.515152, 0.484848, 0.363636, 0.181819]], axis=0)
#Function 4:	-4.939960051262183
outputs = np.append(outputs, [-4.939960051262183], axis=0)

In [ ]:
print(len(inputs))
print(inputs)
print(len(outputs))
print(outputs)

In [50]:
X = inputs
y = outputs

In [51]:
%run ../common_functions.ipynb
# Initialize result collection
query_results = []

In [52]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.01, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.54545455 0.42424242 0.42424242 0.24242424]


In [53]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.05, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.05, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.54545455 0.42424242 0.42424242 0.24242424]


In [54]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='PI', xi=0.1, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('PI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.54545455 0.42424242 0.45454545 0.24242424]


In [55]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=1.0, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 1.0, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.51515152 0.42424242 0.42424242 0.21212121]


In [56]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=2.0, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 2.0, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.51515152 0.39393939 0.39393939 0.18181818]


In [57]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='UCB', kappa=3.0, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('UCB', 3.0, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.51515152 0.48484848 0.36363636 0.18181818]


In [58]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.51515152 0.42424242 0.42424242 0.21212121]


In [59]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.05, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.05, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.51515152 0.42424242 0.42424242 0.21212121]


In [60]:
next_point, acq_vals, grid = select_next_query_multi(X, y, method='EI', xi=0.1, dimension=X.shape[1] - 1, apply_scaling=True)
print("Next query point:", next_point)
score = acq_vals[np.argmax(acq_vals)]
log_query_candidate('EI', 0.1, next_point,score)

Number of features:  4
Dimension of input space: 4
Each axis has 100 points before downsampling
Each axis has 34 points after downsampling
Function will evaluate across: 1336336 points
Mean  1336336
Std   1336336
Next query point: [0.51515152 0.42424242 0.42424242 0.21212121]


In [61]:
find_best_candidate(query_results)

Total number of points to evaluate: 9
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.54545455, 0.42424242, 0.42424242, 0.24242424]), 'score': np.float64(0.6115051740637446), 'dim': 4}
{'method': 'PI', 'xi': 0.05, 'kappa': None, 'x': array([0.54545455, 0.42424242, 0.42424242, 0.24242424]), 'score': np.float64(0.5482034762759976), 'dim': 4}
{'method': 'PI', 'xi': 0.1, 'kappa': None, 'x': array([0.54545455, 0.42424242, 0.45454545, 0.24242424]), 'score': np.float64(0.4730723447571638), 'dim': 4}
{'method': 'UCB', 'xi': None, 'kappa': 1.0, 'x': array([0.51515152, 0.42424242, 0.42424242, 0.21212121]), 'score': np.float64(2.2036718106889084), 'dim': 4}
{'method': 'UCB', 'xi': None, 'kappa': 2.0, 'x': array([0.51515152, 0.39393939, 0.39393939, 0.18181818]), 'score': np.float64(2.826650534853063), 'dim': 4}
{'method': 'UCB', 'xi': None, 'kappa': 3.0, 'x': array([0.51515152, 0.48484848, 0.36363636, 0.18181818]), 'score': np.float64(3.616703214072083), 'dim': 4}
{'method': 'EI', 'xi': 0

{'method': 'UCB',
 'xi': None,
 'kappa': 3.0,
 'x': array([0.51515152, 0.48484848, 0.36363636, 0.18181818]),
 'score': np.float64(3.616703214072083),
 'dim': 4}