In [1]:
import numpy as np

# Load initial input data
inputs = np.load('initial_inputs.npy', allow_pickle=True)
print(len(inputs))
print(inputs)
# Load initial output data
outputs = np.load('initial_outputs.npy', allow_pickle=True)
print(len(outputs))
print(outputs)

30
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.170347

In [2]:
def print_csv(arr):
    """
    Print a NumPy array as CSV:
    - One row per line
    - Comma-separated columns
    - If there's only one row, print each value on a new line
    """
    arr = np.asarray(arr)

    if arr.ndim == 0:
        # Scalar
        print(str(arr.item()))

    elif arr.ndim == 1:
        # 1D: treat as single row → print each value on its own line
        for val in arr:
            print(str(val))

    elif arr.ndim == 2:
        if arr.shape[0] == 1:
            # Single row → print each column value on its own line
            for val in arr[0]:
                print(str(val))
        else:
            # Multiple rows → print comma-separated
            for row in arr:
                print(','.join(map(str, row)))

    else:
        # 3D+ → flatten each leading slice to a row
        reshaped = arr.reshape(arr.shape[0], -1)
        for row in reshaped:
            print(','.join(map(str, row)))
print_csv(inputs)
print_csv(outputs)

0.8969810543559719,0.7256279703482243,0.17540430890241154,0.7016943693717497
0.8893563957199797,0.49958785537696504,0.5392688577643431,0.5087834390633533
0.25094624275233424,0.03369313054735357,0.14538002473552147,0.49493242056497855
0.34696206091432413,0.006250400244917853,0.7605636064368956,0.6130235572343078
0.1248711812207095,0.12977019306510673,0.38440048300130336,0.28707610106061277
0.8013027073487429,0.5002310937156627,0.7066445599562093,0.19510284101191622
0.2477082618994807,0.060445427321989764,0.04218634513719777,0.44132425054403157
0.7467022420948025,0.7570915044306501,0.3693530595537917,0.20656628103766395
0.400665027194423,0.07257425107127335,0.8867682538447798,0.24384228978922717
0.6260705961944015,0.5867512592598441,0.4388057821707446,0.7788576937904925
0.9571352930644363,0.5976443830130996,0.7661138515714809,0.7762099053238541
0.7328124260168783,0.14524997897358805,0.47681271763115285,0.13336573404584584
0.6551154792459779,0.07239182690482326,0.6871517458198465,0.081516